name: git-openssl
on:
  push:
  pull_request:

jobs:
  build-git-openssl-packages
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
